package com.bank.cebos.dto.mobile;

public record MobileProfileResponse(
    Long employeeOnboardingId,
    String employeeRef,
    String status,
    String fullName,
    String fatherName,
    String cnic,
    String mobile,
    String gender,
    String dateOfBirth,
    String cnicIssueDate,
    String cnicExpiryDate,
    String presentAddress,
    String corporateName,
    String corporateClientCode,
    String tradeName,
    String industry,
    String registeredAddress,
    String city,
    String contactPhone,
    String contactEmail,
    String companyRegistrationNo,
    String designation,
    String sourceOfIncome,
    String purposeOfAccount) {}
